### ISSUE TITLE
3.6.4 Documentation (meta bug)

### ISSUE THREAD

**Issue by jrconlin** [mozilla-services/contile#42]
Create Documentation for the system which should include:

* [x] API description and functions
* [ ] Operations and maintenance
* [ ] Emergency Run book
* [ ] Testing strategy document

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/CONSVC-204)
┆epic: General Project Tasks

**Comment by jrconlin** [comment]
NOTE: When a more permanent documentation site is created around this feature, we should make sure that `GET /` requests 302 to the documentation site.

**Comment by jrconlin** [comment]
Unfortunately, some of the elements listed in this issue need to be proprietary due to partner agreements. We'll create a project wiki page that contains the public data soon.
