### ISSUE TITLE
3.7 Testing meta bug

### ISSUE THREAD

**Issue by jrconlin** [mozilla-services/contile#43]
Create tests for the system

 - [ ] Unit testing w/ associated coverage (might be tricky with current rust frameworks)
 - [x] Integration testing with Geolocation tests
 - [x] Load testing w/ molotov load tester (#20)
 - [x] Quarterly Audit schedule and documents

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/CONSVC-203)
┆Epic: Testing

**Comment by data-sync-user** [comment]
➤ Raphael Pierzina commented:

I think we can probably close this ticket. We run unit and integration tests on CI, manually run load tests for new releases and have a Quarterly Audit scheduled.

**Comment by data-sync-user** [comment]
➤ David Durst commented:

Closing this per Raphael’s comment and the fact that the “tricky” note is covered by a separate ticket.

**Comment by data-sync-user** [comment]
➤ David Durst commented:

Items in this meta are handled by separate existing items.
